version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8

  build:
    commands:
      - sam build
      - sam local invoke HelloWorldFunction

  post_build:
    commands:
      - sam package --output-template-file packaged.yaml --s3-bucket linjungz-serverless-cicd-demo --s3-prefix build

artifacts:
  files:
    - packaged.yaml